### ISSUE TITLE
Auth no Redirect to app

### ISSUE THREAD

**Issue by alexlarraga1** [ionicthemes/ionic5-firebase-authentication#3]
Hi, when i authenticate eith google provider opens a apge in mobile browser but does not reditect to te app. 

`signInWithGoogle() {
      return new Promise<FirebaseUserModel>(((resolve, reject) => {
        if (this.platform.is('crodova')){
          this.googlePlus.login({
            'scopes': '', // optional, space-separated list of scopes, If not included or empty, defaults to `profile` and `email`.
            'webClientId': '12345-letters.apps.googleusercontent.com', // optional clientId of your Web application from Credentials settings of your project - On Android, this MUST be included to get an idToken. On iOS, it is not required.
            'offline': true
          }).then((response) => {
            const googleCredential = firebase.auth.GoogleAuthProvider.credential(response.idToken);
            firebase.auth().signInWithCredential(googleCredential)
              .then((user) =>{
                resolve();
              });
          }, (err) => {
            reject(err);
          });
        }
        else {
          this.firebaseAuth.auth
            .signInWithPopup(new firebase.auth.GoogleAuthProvider())
            .then((user) => {
              resolve();
            }, (err) => {
              reject(err);
            })
        }
      }))
  }`

**Comment by albertosoho** [comment]
Same issue here.

**Comment by djabif** [comment]
Updated to Ionic 5. Everything should work now.
