### ISSUE TITLE
Error: node-sass@4.7.2 postinstall: `node scripts/build.js`

### ISSUE THREAD

**Issue by drummerizm29** [ionicthemes/ionic5-firebase-authentication#4]
i got error when 'ionic serve' 

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (C:\Users\xx\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : not installed

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Comment by djabif** [comment]
Try running `npm update node-sass@latest`

**Comment by AlirezaEbrahimkhani** [comment]
try this it works for me 
`npm install node-sass`
`npm install --ignore-scripts`
`bower install`
`npm install`

or this 
`npm install node-sass@latest`

**Comment by djabif** [comment]
Updated to Ionic 5. Everything should work now.
